### ISSUE TITLE
500 Internal Server Error > Oops! Something went wrong. Please reload the page and try again. DEBUG 

### ISSUE THREAD

**Issue by ronnie-depp** [flagrow/bazaar#102]
```
POST http://helptanks.com/api/bazaar/extensions

{
  "errors": [
    {
      "code": 500,
      "title": "Internal server error",
      "detail": "exception 'Composer\\Downloader\\TransportException' with message 'The \"https://packagist.org/packages.json\" file could not be downloaded: allow_url_fopen must be enabled in php.ini (https:// wrapper is disabled in the server configuration by allow_url_fopen=0\nfailed to open stream: no suitable wrapper could be found)' in /home/helptanks/public_html/vendor/composer/composer/src/Composer/Util/RemoteFilesystem.php:515\nStack trace:\n#0 /home/helptanks/public_html/vendor/composer/composer/src/Composer/Util/RemoteFilesystem.php(101): Composer\\Util\\RemoteFilesystem->get('packagist.org', 'https://packagi...', Array, NULL, false)\n#1 /home/helptanks/public_html/vendor/composer/composer/src/Composer/Repository/ComposerRepository.php(664): Composer\\Util\\RemoteFilesystem->getContents('packagist.org', 'https://packagi...', false)\n#2 /home/helptanks/public_html/vendor/composer/composer/src/Composer/Repository/ComposerRepository.php(479): Composer\\Repository\\ComposerRepository->fetchFile('https://packagi...', 'packages.json')\n#3 /home/helptanks/public_html/vendor/composer/composer/src/Composer/Repository/ComposerRepository.php(258): Composer\\Repository\\ComposerRepository->loadRootServerFile()\n#4 /home/helptanks/public_html/vendor/composer/composer/src/Composer/DependencyResolver/Pool.php(99): Composer\\Repository\\ComposerRepository->hasProviders()\n#5 /home/helptanks/public_html/vendor/flagrow/bazaar/src/Composer/Utils/ComposerFileEditor.php(127): Composer\\DependencyResolver\\Pool->addRepository(Object(Composer\\Repository\\CompositeRepository))\n#6 /home/helptanks/public_html/vendor/flagrow/bazaar/src/Composer/Commands/RequireCommand.php(14): Flagrow\\Bazaar\\Composer\\Utils\\ComposerFileEditor->getPool(Object(Flagrow\\Bazaar\\Composer\\Utils\\ComposerIO))\n#7 /home/helptanks/public_html/vendor/flagrow/bazaar/src/Composer/Commands/BaseCommand.php(99): Flagrow\\Bazaar\\Composer\\Commands\\RequireCommand->handle(Array)\n#8 /home/helptanks/public_html/vendor/flagrow/bazaar/src/Composer/ComposerCommand.php(31): Flagrow\\Bazaar\\Composer\\Commands\\BaseCommand->run(Array)\n#9 /home/helptanks/public_html/vendor/flagrow/bazaar/src/Jobs/RequirePackage.php(15): Flagrow\\Bazaar\\Composer\\ComposerCommand->requires('vingle/flarum-s...')\n#10 /home/helptanks/public_html/vendor/flagrow/bazaar/src/Jobs/ComposerJob.php(62): Flagrow\\Bazaar\\Jobs\\RequirePackage->handleComposer(Object(Flagrow\\Bazaar\\Composer\\ComposerCommand), Object(Flagrow\\Bazaar\\Models\\Task))\n#11 /home/helptanks/public_html/vendor/flagrow/bazaar/src/Jobs/ComposerJob.php(100): Flagrow\\Bazaar\\Jobs\\ComposerJob->handle(Object(Flagrow\\Bazaar\\Composer\\ComposerEnvironment), Object(Monolog\\Logger))\n#12 /home/helptanks/public_html/vendor/flagrow/bazaar/src/Extensions/PackageManager.php(51): Flagrow\\Bazaar\\Jobs\\ComposerJob::launchJob(Object(Flagrow\\Bazaar\\Models\\Task))\n#13 /home/helptanks/public_html/vendor/flagrow/bazaar/src/Repositories/ExtensionRepository.php(202): Flagrow\\Bazaar\\Extensions\\PackageManager->requirePackage('vingle/flarum-s...')\n#14 /home/helptanks/public_html/vendor/flagrow/bazaar/src/Api/Controllers/InstallExtensionController.php(49): Flagrow\\Bazaar\\Repositories\\ExtensionRepository->installExtension('vingle/flarum-s...')\n#15 /home/helptanks/public_html/vendor/flarum/core/src/Api/Controller/AbstractSerializeController.php(97): Flagrow\\Bazaar\\Api\\Controllers\\InstallExtensionController->data(Object(Zend\\Stratigility\\Http\\Request), Object(Tobscure\\JsonApi\\Document))\n#16 /home/helptanks/public_html/vendor/flarum/core/src/Api/Controller/AbstractCreateController.php(23): Flarum\\Api\\Controller\\AbstractSerializeController->handle(Object(Zend\\Stratigility\\Http\\Request))\n#17 /home/helptanks/public_html/vendor/flarum/core/src/Http/Handler/ControllerRouteHandler.php(53): Flarum\\Api\\Controller\\AbstractCreateController->handle(Object(Zend\\Stratigility\\Http\\Request))\n#18 /home/helptanks/public_html/vendor/flarum/core/src/Http/Middleware/DispatchRoute.php(69): Flarum\\Http\\Handler\\ControllerRouteHandler->__invoke(Object(Zend\\Stratigility\\Http\\Request), Array)\n#19 /home/helptanks/public_html/vendor/zendframework/zend-stratigility/src/Dispatch.php(212): Flarum\\Http\\Middleware\\DispatchRoute->__invoke(Object(Zend\\Stratigility\\Http\\Request), Object(Zend\\Stratigility\\Http\\Response), Object(Zend\\Stratigility\\Next))\n#20 /home/helptanks/public_html/vendor/zendframework/zend-stratigility/src/Dispatch.php(88): Zend\\Stratigility\\Dispatch->dispatchCallableMiddleware(Object(Flarum\\Http\\Middleware\\DispatchRoute), Object(Zend\\Stratigility\\Next), Object(Zend\\Stratigility\\Http\\Request), Object(Zend\\Stratigility\\Http\\Response), NULL)\n#21 /home/helptanks/public_html/vendor/zendframework/zend-stratigility/src/Next.php(160): Zend\\Stratigility\\Dispatch->__invoke(Object(Zend\\Stratigility\\Route), NULL, Object(Zend\\Stratigility\\Http\\Request), Object(Zend\\Stratigility\\Http\\Response), Object(Zend\\Stratigility\\Next))\n#22 /home/helptanks/public_html/vendor/flarum/core/src/Http/Middleware/SetLocale.php(51): Zend\\Stratigility\\Next->__invoke(Object(Zend\\Stratigility\\Http\\Request), Object(Zend\\Stratigility\\Http\\Response))\n#23 /home/helptanks/public_html/vendor/zendframework/zend-stratigility/src/Dispatch.php(212): Flarum\\Http\\Middleware\\SetLocale->__invoke(Object(Zend\\Stratigility\\Http\\Request), Object(Zend\\Stratigility\\Http\\Response), Object(Zend\\Stratigility\\Next))\n#24 /home/helptanks/public_html/vendor/zendframework/zend-stratigility/src/Dispatch.php(88): Zend\\Stratigility\\Dispatch->dispatchCallableMiddleware(Object(Flarum\\Http\\Middleware\\SetLocale), Object(Zend\\Stratigility\\Next), Object(Zend\\Stratigility\\Http\\Request), Object(Zend\\Stratigility\\Http\\Response), NULL)\n#25 /home/helptanks/public_html/vendor/zendframework/zend-stratigility/src/Next.php(160): Zend\\Stratigility\\Dispatch->__invoke(Object(Zend\\Stratigility\\Route), NULL, Object(Zend\\Stratigility\\Http\\Request), Object(Zend\\Stratigility\\Http\\Response), Object(Zend\\Stratigility\\Next))\n#26 /home/helptanks/public_html/vendor/flarum/core/src/Http/Middleware/AuthenticateWithHeader.php(58): Zend\\Stratigility\\Next->__invoke(Object(Zend\\Stratigility\\Http\\Request), Object(Zend\\Stratigility\\Http\\Response))\n#27 /home/helptanks/public_html/vendor/zendframework/zend-stratigility/src/Dispatch.php(212): Flarum\\Http\\Middleware\\AuthenticateWithHeader->__invoke(Object(Zend\\Stratigility\\Http\\Request), Object(Zend\\Stratigility\\Http\\Response), Object(Zend\\Stratigility\\Next))\n#28 /home/helptanks/public_html/vendor/zendframework/zend-stratigility/src/Dispatch.php(88): Zend\\Stratigility\\Dispatch->dispatchCallableMiddleware(Object(Flarum\\Http\\Middleware\\AuthenticateWithHeader), Object(Zend\\Stratigility\\Next), Object(Zend\\Stratigility\\Http\\Request), Object(Zend\\Stratigility\\Http\\Response), NULL)\n#29 /home/helptanks/public_html/vendor/zendframework/zend-stratigility/src/Next.php(160): Zend\\Stratigility\\Dispatch->__invoke(Object(Zend\\Stratigility\\Route), NULL, Object(Zend\\Stratigility\\Http\\Request), Object(Zend\\Stratigility\\Http\\Response), Object(Zend\\Stratigility\\Next))\n#30 /home/helptanks/public_html/vendor/flarum/core/src/Http/Middleware/AuthenticateWithSession.php(36): Zend\\Stratigility\\Next->__invoke(Object(Zend\\Stratigility\\Http\\Request), Object(Zend\\Stratigility\\Http\\Response))\n#31 /home/helptanks/public_html/vendor/zendframework/zend-stratigility/src/Dispatch.php(212): Flarum\\Http\\Middleware\\AuthenticateWithSession->__invoke(Object(Zend\\Stratigility\\Http\\Request), Object(Zend\\Stratigility\\Http\\Response), Object(Zend\\Stratigility\\Next))\n#32 /home/helptanks/public_html/vendor/zendframework/zend-stratigility/src/Dispatch.php(88): Zend\\Stratigility\\Dispatch->dispatchCallableMiddleware(Object(Flarum\\Http\\Middleware\\AuthenticateWithSession), Object(Zend\\Stratigility\\Next), Object(Zend\\Stratigility\\Http\\Request), Object(Zend\\Stratigility\\Http\\Response), NULL)\n#33 /home/helptanks/public_html/vendor/zendframework/zend-stratigility/src/Next.php(160): Zend\\Stratigility\\Dispatch->__invoke(Object(Zend\\Stratigility\\Route), NULL, Object(Zend\\Stratigility\\Http\\Request), Object(Zend\\Stratigility\\Http\\Response), Object(Zend\\Stratigility\\Next))\n#34 /home/helptanks/public_html/vendor/flarum/core/src/Http/Middleware/RememberFromCookie.php(39): Zend\\Stratigility\\Next->__invoke(Object(Zend\\Stratigility\\Http\\Request), Object(Zend\\Stratigility\\Http\\Response))\n#35 /home/helptanks/public_html/vendor/zendframework/zend-stratigility/src/Dispatch.php(212): Flarum\\Http\\Middleware\\RememberFromCookie->__invoke(Object(Zend\\Stratigility\\Http\\Request), Object(Zend\\Stratigility\\Http\\Response), Object(Zend\\Stratigility\\Next))\n#36 /home/helptanks/public_html/vendor/zendframework/zend-stratigility/src/Dispatch.php(88): Zend\\Stratigility\\Dispatch->dispatchCallableMiddleware(Object(Flarum\\Http\\Middleware\\RememberFromCookie), Object(Zend\\Stratigility\\Next), Object(Zend\\Stratigility\\Http\\Request), Object(Zend\\Stratigility\\Http\\Response), NULL)\n#37 /home/helptanks/public_html/vendor/zendframework/zend-stratigility/src/Next.php(160): Zend\\Stratigility\\Dispatch->__invoke(Object(Zend\\Stratigility\\Route), NULL, Object(Zend\\Stratigility\\Http\\Request), Object(Zend\\Stratigility\\Http\\Response), Object(Zend\\Stratigility\\Next))\n#38 /home/helptanks/public_html/vendor/flarum/core/src/Http/Middleware/StartSession.php(48): Zend\\Stratigility\\Next->__invoke(Object(Zend\\Stratigility\\Http\\Request), Object(Zend\\Stratigility\\Http\\Response))\n#39 /home/helptanks/public_html/vendor/zendframework/zend-stratigility/src/Dispatch.php(212): Flarum\\Http\\Middleware\\StartSession->__invoke(Object(Zend\\Stratigility\\Http\\Request), Object(Zend\\Stratigility\\Http\\Response), Object(Zend\\Stratigility\\Next))\n#40 /home/helptanks/public_html/vendor/zendframework/zend-stratigility/src/Dispatch.php(88): Zend\\Stratigility\\Dispatch->dispatchCallableMiddleware(Object(Flarum\\Http\\Middleware\\StartSession), Object(Zend\\Stratigility\\Next), Object(Zend\\Stratigility\\Http\\Request), Object(Zend\\Stratigility\\Http\\Response), NULL)\n#41 /home/helptanks/public_html/vendor/zendframework/zend-stratigility/src/Next.php(160): Zend\\Stratigility\\Dispatch->__invoke(Object(Zend\\Stratigility\\Route), NULL, Object(Zend\\Stratigility\\Http\\Request), Object(Zend\\Stratigility\\Http\\Response), Object(Zend\\Stratigility\\Next))\n#42 /home/helptanks/public_html/vendor/flarum/core/src/Api/Middleware/FakeHttpMethods.php(33): Zend\\Stratigility\\Next->__invoke(Object(Zend\\Stratigility\\Http\\Request), Object(Zend\\Stratigility\\Http\\Response))\n#43 /home/helptanks/public_html/vendor/zendframework/zend-stratigility/src/Dispatch.php(212): Flarum\\Api\\Middleware\\FakeHttpMethods->__invoke(Object(Zend\\Stratigility\\Http\\Request), Object(Zend\\Stratigility\\Http\\Response), Object(Zend\\Stratigility\\Next))\n#44 /home/helptanks/public_html/vendor/zendframework/zend-stratigility/src/Dispatch.php(88): Zend\\Stratigility\\Dispatch->dispatchCallableMiddleware(Object(Flarum\\Api\\Middleware\\FakeHttpMethods), Object(Zend\\Stratigility\\Next), Object(Zend\\Stratigility\\Http\\Request), Object(Zend\\Stratigility\\Http\\Response), NULL)\n#45 /home/helptanks/public_html/vendor/zendframework/zend-stratigility/src/Next.php(160): Zend\\Stratigility\\Dispatch->__invoke(Object(Zend\\Stratigility\\Route), NULL, Object(Zend\\Stratigility\\Http\\Request), Object(Zend\\Stratigility\\Http\\Response), Object(Zend\\Stratigility\\Next))\n#46 /home/helptanks/public_html/vendor/flarum/core/src/Http/Middleware/ParseJsonBody.php(31): Zend\\Stratigility\\Next->__invoke(Object(Zend\\Stratigility\\Http\\Request), Object(Zend\\Stratigility\\Http\\Response))\n#47 /home/helptanks/public_html/vendor/zendframework/zend-stratigility/src/Dispatch.php(212): Flarum\\Http\\Middleware\\ParseJsonBody->__invoke(Object(Zend\\Stratigility\\Http\\Request), Object(Zend\\Stratigility\\Http\\Response), Object(Zend\\Stratigility\\Next))\n#48 /home/helptanks/public_html/vendor/zendframework/zend-stratigility/src/Dispatch.php(88): Zend\\Stratigility\\Dispatch->dispatchCallableMiddleware(Object(Flarum\\Http\\Middleware\\ParseJsonBody), Object(Zend\\Stratigility\\Next), Object(Zend\\Stratigility\\Http\\Request), Object(Zend\\Stratigility\\Http\\Response), NULL)\n#49 /home/helptanks/public_html/vendor/zendframework/zend-stratigility/src/Next.php(160): Zend\\Stratigility\\Dispatch->__invoke(Object(Zend\\Stratigility\\Route), NULL, Object(Zend\\Stratigility\\Http\\Request), Object(Zend\\Stratigility\\Http\\Response), Object(Zend\\Stratigility\\Next))\n#50 /home/helptanks/public_html/vendor/flarum/core/src/Api/Middleware/HandleErrors.php(45): Zend\\Stratigility\\Next->__invoke(Object(Zend\\Stratigility\\Http\\Request), Object(Zend\\Stratigility\\Http\\Response))\n#51 /home/helptanks/public_html/vendor/zendframework/zend-stratigility/src/Dispatch.php(212): Flarum\\Api\\Middleware\\HandleErrors->__invoke(Object(Zend\\Stratigility\\Http\\Request), Object(Zend\\Stratigility\\Http\\Response), Object(Zend\\Stratigility\\Next))\n#52 /home/helptanks/public_html/vendor/zendframework/zend-stratigility/src/Dispatch.php(88): Zend\\Stratigility\\Dispatch->dispatchCallableMiddleware(Object(Flarum\\Api\\Middleware\\HandleErrors), Object(Zend\\Stratigility\\Next), Object(Zend\\Stratigility\\Http\\Request), Object(Zend\\Stratigility\\Http\\Response), NULL)\n#53 /home/helptanks/public_html/vendor/zendframework/zend-stratigility/src/Next.php(160): Zend\\Stratigility\\Dispatch->__invoke(Object(Zend\\Stratigility\\Route), NULL, Object(Zend\\Stratigility\\Http\\Request), Object(Zend\\Stratigility\\Http\\Response), Object(Zend\\Stratigility\\Next))\n#54 /home/helptanks/public_html/vendor/zendframework/zend-stratigility/src/MiddlewarePipe.php(111): Zend\\Stratigility\\Next->__invoke(Object(Zend\\Stratigility\\Http\\Request), Object(Zend\\Stratigility\\Http\\Response))\n#55 /home/helptanks/public_html/vendor/flarum/core/src/Http/AbstractServer.php(55): Zend\\Stratigility\\MiddlewarePipe->__invoke(Object(Zend\\Diactoros\\ServerRequest), Object(Zend\\Diactoros\\Response), Object(Zend\\Stratigility\\NoopFinalHandler))\n#56 /home/helptanks/public_html/vendor/zendframework/zend-diactoros/src/Server.php(157): Flarum\\Http\\AbstractServer->__invoke(Object(Zend\\Diactoros\\ServerRequest), Object(Zend\\Diactoros\\Response), Object(Zend\\Stratigility\\NoopFinalHandler))\n#57 /home/helptanks/public_html/vendor/flarum/core/src/Http/AbstractServer.php(36): Zend\\Diactoros\\Server->listen(Object(Zend\\Stratigility\\NoopFinalHandler))\n#58 /home/helptanks/public_html/api.php(16): Flarum\\Http\\AbstractServer->listen()\n#59 {main}"
    }
  ]
}
```
POST http://helptanks.com/api/bazaar/extensions

{
  "errors": [
    {
      "code": 500,
      "title": "Internal server error",
      "detail": "exception 'Composer\\Downloader\\TransportException'
### Steps to reproduce

1. 
2. 
3. 

### Expected behaviour

Tell us what should happen

### Actual behaviour

Tell us what happens instead

### Configuration

**Operating system:** linux

**Version of Bazaar:** 0.2.4
**Version of Flarum:** 0.1.0-beta.7
**Other extensions:** 

<details><summary>**Logs**:</summary>
[2017-12-18 14:00:35] production.ERROR: The "https://packagist.org/packages.json" file could not be downloaded: allow_url_fopen must be enabled in php.ini (https:// wrapper is disabled in the server configuration by allow_url_fopen=0
failed to open stream: no suitable wrapper could be found) 

</details>

**Comment by luceos** [comment]
You have to allow outgoing requests on your server. Enable `allow_url_fopen` in your php.ini or webhosting panel.

**Comment by ronnie-depp** [comment]
i'm on shared hosting. what can I do ? Shall shift to VPS or Dedicated Server? @luceos

**Comment by luceos** [comment]
Ask your hosting provider whether they can enable allow_url_fopen would be the first step.
