### ISSUE TITLE
Get requests error

### ISSUE THREAD

**Issue by KazeroG** [flagrow/bazaar#113]
### Steps to reproduce

juste install bazaar and go to the bazaar tab

### Expected behaviour

juste have access to the bazaar

### Actual behaviour

Big error 500 

### Configuration

**Operating system: apache on hostinger** 

**Version of Bazaar: "flagrow/bazaar": "^0.2.4"** 
**Version of Flarum:beta7** 
**Other extensions: yes**

that my composer file : 
```
{
    "name": "flarum/flarum",
    "description": "Delightfully simple forum software.",
    "type": "project",
    "keywords": ["forum", "discussion"],
    "homepage": "http://flarum.org",
    "license": "MIT",
    "authors": [
        {
            "name": "Toby Zerner",
            "email": "toby.zerner@gmail.com"
        },
        {
            "name": "Franz Liedke",
            "email": "franz@develophp.org"
        }
    ],
    "support": {
        "issues": "https://github.com/flarum/core/issues",
        "source": "https://github.com/flarum/flarum",
        "docs": "http://flarum.org/docs"
    },
    "require": {
        "flarum/core": "^0.1.0",
        "flarum/flarum-ext-approval": "^0.1.0",
        "flarum/flarum-ext-bbcode": "^0.1.0@beta",
        "flarum/flarum-ext-emoji": "^0.1.0",
        "flarum/flarum-ext-english": "^0.1.0",
        "flarum/flarum-ext-flags": "^0.1.0",
        "flarum/flarum-ext-likes": "^0.1.0",
        "flarum/flarum-ext-lock": "^0.1.0",
        "flarum/flarum-ext-markdown": "^0.1.0",
        "flarum/flarum-ext-mentions": "^0.1.0",
        "flarum/flarum-ext-sticky": "^0.1.0",
        "flarum/flarum-ext-subscriptions": "^0.1.0",
        "flarum/flarum-ext-suspend": "^0.1.0",
        "flarum/flarum-ext-tags": "^0.1.0",
        "flagrow/upload": "^0.6.0",
        "milescellar/flarum-ext-french": "^1.1",
        "sijad/flarum-ext-links": "^0.1.0@beta",
        "avatar4eg/flarum-ext-users-list": "^0.1.1",
        "clarkwinkelmann/flarum-ext-emojionearea": "^0.1.2",
        "flagrow/byobu": "^0.1.2",
        "davis/flarum-ext-socialprofile": "^0.2.3",
        "datitisev/flarum-ext-dashboard": "^0.1.0@beta",
        "vingle/flarum-share-social": "^0.1.0",
        "reflar/user-management": "^0.1.4",
        "sijad/flarum-ext-recaptcha": "^0.0.2",
        "davis/flarum-ext-customfooter": "^0.1.0@beta",
        "reflar/gamification": "^3.0",
        "terabin/flarum-ext-sitemap": "^1.0@beta",
        "hyn/flarum-default-group": "^0.5.0",
        "sijad/flarum-ext-auth-steam": "^0.1.10",
        "isaa/flarum-isaa-opengraph": "^0.1.0",
        "antoinefr/flarum-ext-online": "^0.3.0",
        "wuethrich44/flarum-ext-sso": "^1.1",
        "flarumchina/flarum-ext-mediaembed-pro": "^0.3.6",
        "flagrow/user-directory": "^0.1.0",
        "issyrocks12/flarum-ext-filter": "^1.2",
        "flagrow/flarum-ext-latex": "^0.1.1",
        "sledov/flarum-ext-quill": "^0.1.0@beta",
        "antoinefr/flarum-ext-bbcode-fa": "^0.1.1",
        "oe800/flarum-ext-bbcode-cards": "^0.1.4",
        "oe800/flarum-ext-bbcode-alerts": "^0.1.6",
        "ganuonglachanh/flarum-ext-search": "^0.3.0",
        "sides/flarum-ext-autovid": "^0.1.0@beta",
        "matpompili/flarum-imgur-upload": "^1.0",
        "flagrow/fonts": "^0.1.2",
        "oe800/flarum-ext-bbcode-special": "^0.1.5",
        "flagrow/linguist": "^0.1.2",
        "oe800/flarum-ext-bbcode-bars": "^0.1.5",
        "oe800/flarum-ext-bbcode-pastebin": "^0.1.2",
        "empewoow/flarum-ext-auth-redirect": "^0.1.0@beta",
        "zeokat/flarum-ext-seoslugs": "^0.1.1",
        "reflar/polls": "^1.1",
        "flagrow/impersonate": "^0.1.0",
        "dsgnr/flarum-ext-customcss": "^0.1.1@beta",
        "oe800/flarum-ext-bbcode-tables": "^0.1.0",
        "sijad/flarum-ext-pages": "^0.1.0@beta",
        "michelf/php-markdown": "^1.8",
        "ganuonglachanh/flarum-ext-markdown-editor": "^0.9.0",
        "flagrow/flarum-api-client": "^0.1.2",
        "fixer112/flarum-frontpage": "^0.1.1",
        "flagrow/bazaar": "^0.2.4"
    },
    "require-dev": {
        "franzl/studio": "^0.11.0"
    },
    "config": {
        "preferred-install": "dist"
    },
    "minimum-stability": "beta",
    "prefer-stable": true
}
 
```

<details><summary>**Logs**:</summary>

```
GET https://manslandlife.tk/forum/v2/api/bazaar/extensions?filter%5Bsearch%5D=

{
  "errors": [
    {
      "code": 500,
      "title": "Internal server error",
      "detail": "LogicException: Lost connection and no reconnector available. in /home/u857997072/public_html/forum/v2/vendor/illuminate/database/Connection.php:715\nStack trace:\n#0 /home/u857997072/public_html/forum/v2/vendor/illuminate/database/Connection.php(684): Illuminate\\Database\\Connection->reconnect()\n#1 /home/u857997072/public_html/forum/v2/vendor/illuminate/database/Connection.php(625): Illuminate\\Database\\Connection->tryAgainIfCausedByLostConnection(Object(Illuminate\\Database\\QueryException), 'select exists(s...', Array, Object(Closure))\n#2 /home/u857997072/public_html/forum/v2/vendor/illuminate/database/Connection.php(324): Illuminate\\Database\\Connection->run('select exists(s...', Array, Object(Closure))\n#3 /home/u857997072/public_html/forum/v2/vendor/illuminate/database/Query/Builder.php(1637): Illuminate\\Database\\Connection->select('select exists(s...', Array, true)\n#4 /home/u857997072/public_html/forum/v2/vendor/flarum/core/src/Settings/DatabaseSettingsRepository.php(43): Illuminate\\Database\\Query\\Builder->exists()\n#5 /home/u857997072/public_html/forum/v2/vendor/flarum/core/src/Settings/MemoryCacheSettingsRepository.php(52): Flarum\\Settings\\DatabaseSettingsRepository->set('flagrow.bazaar....', 1)\n#6 /home/u857997072/public_html/forum/v2/vendor/flagrow/bazaar/src/Search/FlagrowApi.php(99): Flarum\\Settings\\MemoryCacheSettingsRepository->set('flagrow.bazaar....', 1)\n#7 /home/u857997072/public_html/forum/v2/vendor/guzzlehttp/promises/src/FulfilledPromise.php(39): Flagrow\\Bazaar\\Search\\FlagrowApi->Flagrow\\Bazaar\\Search\\{closure}(Object(GuzzleHttp\\Psr7\\Response))\n#8 /home/u857997072/public_html/forum/v2/vendor/guzzlehttp/promises/src/TaskQueue.php(47): GuzzleHttp\\Promise\\FulfilledPromise::GuzzleHttp\\Promise\\{closure}()\n#9 /home/u857997072/public_html/forum/v2/vendor/guzzlehttp/promises/src/Promise.php(246): GuzzleHttp\\Promise\\TaskQueue->run(true)\n#10 /home/u857997072/public_html/forum/v2/vendor/guzzlehttp/promises/src/Promise.php(223): GuzzleHttp\\Promise\\Promise->invokeWaitFn()\n#11 /home/u857997072/public_html/forum/v2/vendor/guzzlehttp/promises/src/Promise.php(62): GuzzleHttp\\Promise\\Promise->waitIfPending()\n#12 /home/u857997072/public_html/forum/v2/vendor/guzzlehttp/guzzle/src/Client.php(131): GuzzleHttp\\Promise\\Promise->wait()\n#13 /home/u857997072/public_html/forum/v2/vendor/guzzlehttp/guzzle/src/Client.php(89): GuzzleHttp\\Client->request('get', 'packages', Array)\n#14 /home/u857997072/public_html/forum/v2/vendor/flagrow/bazaar/src/Repositories/ExtensionRepository.php(83): GuzzleHttp\\Client->__call('get', Array)\n#15 /home/u857997072/public_html/forum/v2/vendor/flagrow/bazaar/src/Traits/Cachable.php(17): Flagrow\\Bazaar\\Repositories\\ExtensionRepository->Flagrow\\Bazaar\\Repositories\\{closure}()\n#16 /home/u857997072/public_html/forum/v2/vendor/flagrow/bazaar/src/Repositories/ExtensionRepository.php(88): Flagrow\\Bazaar\\Repositories\\ExtensionRepository->getOrSetCache('flagrow.io.sear...', Object(Closure))\n#17 /home/u857997072/public_html/forum/v2/vendor/flagrow/bazaar/src/Repositories/ExtensionRepository.php(132): Flagrow\\Bazaar\\Repositories\\ExtensionRepository->allExtensionsFromClient()\n#18 /home/u857997072/public_html/forum/v2/vendor/flagrow/bazaar/src/Api/Controllers/ListExtensionController.php(47): Flagrow\\Bazaar\\Repositories\\ExtensionRepository->index(Array)\n#19 /home/u857997072/public_html/forum/v2/vendor/flarum/core/src/Api/Controller/AbstractSerializeController.php(97): Flagrow\\Bazaar\\Api\\Controllers\\ListExtensionController->data(Object(Zend\\Stratigility\\Http\\Request), Object(Tobscure\\JsonApi\\Document))\n#20 /home/u857997072/public_html/forum/v2/vendor/flarum/core/src/Http/Handler/ControllerRouteHandler.php(53): Flarum\\Api\\Controller\\AbstractSerializeController->handle(Object(Zend\\Stratigility\\Http\\Request))\n#21 /home/u857997072/public_html/forum/v2/vendor/flarum/core/src/Http/Middleware/DispatchRoute.php(69): Flarum\\Http\\Handler\\ControllerRouteHandler->__invoke(Object(Zend\\Stratigility\\Http\\Request), Array)\n#22 /home/u857997072/public_html/forum/v2/vendor/zendframework/zend-stratigility/src/Dispatch.php(212): Flarum\\Http\\Middleware\\DispatchRoute->__invoke(Object(Zend\\Stratigility\\Http\\Request), Object(Zend\\Stratigility\\Http\\Response), Object(Zend\\Stratigility\\Next))\n#23 /home/u857997072/public_html/forum/v2/vendor/zendframework/zend-stratigility/src/Dispatch.php(88): Zend\\Stratigility\\Dispatch->dispatchCallableMiddleware(Object(Flarum\\Http\\Middleware\\DispatchRoute), Object(Zend\\Stratigility\\Next), Object(Zend\\Stratigility\\Http\\Request), Object(Zend\\Stratigility\\Http\\Response), NULL)\n#24 /home/u857997072/public_html/forum/v2/vendor/zendframework/zend-stratigility/src/Next.php(160): Zend\\Stratigility\\Dispatch->__invoke(Object(Zend\\Stratigility\\Route), NULL, Object(Zend\\Stratigility\\Http\\Request), Object(Zend\\Stratigility\\Http\\Response), Object(Zend\\Stratigility\\Next))\n#25 /home/u857997072/public_html/forum/v2/vendor/flarum/core/src/Http/Middleware/SetLocale.php(51): Zend\\Stratigility\\Next->__invoke(Object(Zend\\Stratigility\\Http\\Request), Object(Zend\\Stratigility\\Http\\Response))\n#26 /home/u857997072/public_html/forum/v2/vendor/zendframework/zend-stratigility/src/Dispatch.php(212): Flarum\\Http\\Middleware\\SetLocale->__invoke(Object(Zend\\Stratigility\\Http\\Request), Object(Zend\\Stratigility\\Http\\Response), Object(Zend\\Stratigility\\Next))\n#27 /home/u857997072/public_html/forum/v2/vendor/zendframework/zend-stratigility/src/Dispatch.php(88): Zend\\Stratigility\\Dispatch->dispatchCallableMiddleware(Object(Flarum\\Http\\Middleware\\SetLocale), Object(Zend\\Stratigility\\Next), Object(Zend\\Stratigility\\Http\\Request), Object(Zend\\Stratigility\\Http\\Response), NULL)\n#28 /home/u857997072/public_html/forum/v2/vendor/zendframework/zend-stratigility/src/Next.php(160): Zend\\Stratigility\\Dispatch->__invoke(Object(Zend\\Stratigility\\Route), NULL, Object(Zend\\Stratigility\\Http\\Request), Object(Zend\\Stratigility\\Http\\Response), Object(Zend\\Stratigility\\Next))\n#29 /home/u857997072/public_html/forum/v2/vendor/flarum/core/src/Http/Middleware/AuthenticateWithHeader.php(58): Zend\\Stratigility\\Next->__invoke(Object(Zend\\Stratigility\\Http\\Request), Object(Zend\\Stratigility\\Http\\Response))\n#30 /home/u857997072/public_html/forum/v2/vendor/zendframework/zend-stratigility/src/Dispatch.php(212): Flarum\\Http\\Middleware\\AuthenticateWithHeader->__invoke(Object(Zend\\Stratigility\\Http\\Request), Object(Zend\\Stratigility\\Http\\Response), Object(Zend\\Stratigility\\Next))\n#31 /home/u857997072/public_html/forum/v2/vendor/zendframework/zend-stratigility/src/Dispatch.php(88): Zend\\Stratigility\\Dispatch->dispatchCallableMiddleware(Object(Flarum\\Http\\Middleware\\AuthenticateWithHeader), Object(Zend\\Stratigility\\Next), Object(Zend\\Stratigility\\Http\\Request), Object(Zend\\Stratigility\\Http\\Response), NULL)\n#32 /home/u857997072/public_html/forum/v2/vendor/zendframework/zend-stratigility/src/Next.php(160): Zend\\Stratigility\\Dispatch->__invoke(Object(Zend\\Stratigility\\Route), NULL, Object(Zend\\Stratigility\\Http\\Request), Object(Zend\\Stratigility\\Http\\Response), Object(Zend\\Stratigility\\Next))\n#33 /home/u857997072/public_html/forum/v2/vendor/flarum/core/src/Http/Middleware/AuthenticateWithSession.php(36): Zend\\Stratigility\\Next->__invoke(Object(Zend\\Stratigility\\Http\\Request), Object(Zend\\Stratigility\\Http\\Response))\n#34 /home/u857997072/public_html/forum/v2/vendor/zendframework/zend-stratigility/src/Dispatch.php(212): Flarum\\Http\\Middleware\\AuthenticateWithSession->__invoke(Object(Zend\\Stratigility\\Http\\Request), Object(Zend\\Stratigility\\Http\\Response), Object(Zend\\Stratigility\\Next))\n#35 /home/u857997072/public_html/forum/v2/vendor/zendframework/zend-stratigility/src/Dispatch.php(88): Zend\\Stratigility\\Dispatch->dispatchCallableMiddleware(Object(Flarum\\Http\\Middleware\\AuthenticateWithSession), Object(Zend\\Stratigility\\Next), Object(Zend\\Stratigility\\Http\\Request), Object(Zend\\Stratigility\\Http\\Response), NULL)\n#36 /home/u857997072/public_html/forum/v2/vendor/zendframework/zend-stratigility/src/Next.php(160): Zend\\Stratigility\\Dispatch->__invoke(Object(Zend\\Stratigility\\Route), NULL, Object(Zend\\Stratigility\\Http\\Request), Object(Zend\\Stratigility\\Http\\Response), Object(Zend\\Stratigility\\Next))\n#37 /home/u857997072/public_html/forum/v2/vendor/flarum/core/src/Http/Middleware/RememberFromCookie.php(39): Zend\\Stratigility\\Next->__invoke(Object(Zend\\Stratigility\\Http\\Request), Object(Zend\\Stratigility\\Http\\Response))\n#38 /home/u857997072/public_html/forum/v2/vendor/zendframework/zend-stratigility/src/Dispatch.php(212): Flarum\\Http\\Middleware\\RememberFromCookie->__invoke(Object(Zend\\Stratigility\\Http\\Request), Object(Zend\\Stratigility\\Http\\Response), Object(Zend\\Stratigility\\Next))\n#39 /home/u857997072/public_html/forum/v2/vendor/zendframework/zend-stratigility/src/Dispatch.php(88): Zend\\Stratigility\\Dispatch->dispatchCallableMiddleware(Object(Flarum\\Http\\Middleware\\RememberFromCookie), Object(Zend\\Stratigility\\Next), Object(Zend\\Stratigility\\Http\\Request), Object(Zend\\Stratigility\\Http\\Response), NULL)\n#40 /home/u857997072/public_html/forum/v2/vendor/zendframework/zend-stratigility/src/Next.php(160): Zend\\Stratigility\\Dispatch->__invoke(Object(Zend\\Stratigility\\Route), NULL, Object(Zend\\Stratigility\\Http\\Request), Object(Zend\\Stratigility\\Http\\Response), Object(Zend\\Stratigility\\Next))\n#41 /home/u857997072/public_html/forum/v2/vendor/flarum/core/src/Http/Middleware/StartSession.php(48): Zend\\Stratigility\\Next->__invoke(Object(Zend\\Stratigility\\Http\\Request), Object(Zend\\Stratigility\\Http\\Response))\n#42 /home/u857997072/public_html/forum/v2/vendor/zendframework/zend-stratigility/src/Dispatch.php(212): Flarum\\Http\\Middleware\\StartSession->__invoke(Object(Zend\\Stratigility\\Http\\Request), Object(Zend\\Stratigility\\Http\\Response), Object(Zend\\Stratigility\\Next))\n#43 /home/u857997072/public_html/forum/v2/vendor/zendframework/zend-stratigility/src/Dispatch.php(88): Zend\\Stratigility\\Dispatch->dispatchCallableMiddleware(Object(Flarum\\Http\\Middleware\\StartSession), Object(Zend\\Stratigility\\Next), Object(Zend\\Stratigility\\Http\\Request), Object(Zend\\Stratigility\\Http\\Response), NULL)\n#44 /home/u857997072/public_html/forum/v2/vendor/zendframework/zend-stratigility/src/Next.php(160): Zend\\Stratigility\\Dispatch->__invoke(Object(Zend\\Stratigility\\Route), NULL, Object(Zend\\Stratigility\\Http\\Request), Object(Zend\\Stratigility\\Http\\Response), Object(Zend\\Stratigility\\Next))\n#45 /home/u857997072/public_html/forum/v2/vendor/flarum/core/src/Api/Middleware/FakeHttpMethods.php(33): Zend\\Stratigility\\Next->__invoke(Object(Zend\\Stratigility\\Http\\Request), Object(Zend\\Stratigility\\Http\\Response))\n#46 /home/u857997072/public_html/forum/v2/vendor/zendframework/zend-stratigility/src/Dispatch.php(212): Flarum\\Api\\Middleware\\FakeHttpMethods->__invoke(Object(Zend\\Stratigility\\Http\\Request), Object(Zend\\Stratigility\\Http\\Response), Object(Zend\\Stratigility\\Next))\n#47 /home/u857997072/public_html/forum/v2/vendor/zendframework/zend-stratigility/src/Dispatch.php(88): Zend\\Stratigility\\Dispatch->dispatchCallableMiddleware(Object(Flarum\\Api\\Middleware\\FakeHttpMethods), Object(Zend\\Stratigility\\Next), Object(Zend\\Stratigility\\Http\\Request), Object(Zend\\Stratigility\\Http\\Response), NULL)\n#48 /home/u857997072/public_html/forum/v2/vendor/zendframework/zend-stratigility/src/Next.php(160): Zend\\Stratigility\\Dispatch->__invoke(Object(Zend\\Stratigility\\Route), NULL, Object(Zend\\Stratigility\\Http\\Request), Object(Zend\\Stratigility\\Http\\Response), Object(Zend\\Stratigility\\Next))\n#49 /home/u857997072/public_html/forum/v2/vendor/flarum/core/src/Http/Middleware/ParseJsonBody.php(31): Zend\\Stratigility\\Next->__invoke(Object(Zend\\Stratigility\\Http\\Request), Object(Zend\\Stratigility\\Http\\Response))\n#50 /home/u857997072/public_html/forum/v2/vendor/zendframework/zend-stratigility/src/Dispatch.php(212): Flarum\\Http\\Middleware\\ParseJsonBody->__invoke(Object(Zend\\Stratigility\\Http\\Request), Object(Zend\\Stratigility\\Http\\Response), Object(Zend\\Stratigility\\Next))\n#51 /home/u857997072/public_html/forum/v2/vendor/zendframework/zend-stratigility/src/Dispatch.php(88): Zend\\Stratigility\\Dispatch->dispatchCallableMiddleware(Object(Flarum\\Http\\Middleware\\ParseJsonBody), Object(Zend\\Stratigility\\Next), Object(Zend\\Stratigility\\Http\\Request), Object(Zend\\Stratigility\\Http\\Response), NULL)\n#52 /home/u857997072/public_html/forum/v2/vendor/zendframework/zend-stratigility/src/Next.php(160): Zend\\Stratigility\\Dispatch->__invoke(Object(Zend\\Stratigility\\Route), NULL, Object(Zend\\Stratigility\\Http\\Request), Object(Zend\\Stratigility\\Http\\Response), Object(Zend\\Stratigility\\Next))\n#53 /home/u857997072/public_html/forum/v2/vendor/flarum/core/src/Api/Middleware/HandleErrors.php(45): Zend\\Stratigility\\Next->__invoke(Object(Zend\\Stratigility\\Http\\Request), Object(Zend\\Stratigility\\Http\\Response))\n#54 /home/u857997072/public_html/forum/v2/vendor/zendframework/zend-stratigility/src/Dispatch.php(212): Flarum\\Api\\Middleware\\HandleErrors->__invoke(Object(Zend\\Stratigility\\Http\\Request), Object(Zend\\Stratigility\\Http\\Response), Object(Zend\\Stratigility\\Next))\n#55 /home/u857997072/public_html/forum/v2/vendor/zendframework/zend-stratigility/src/Dispatch.php(88): Zend\\Stratigility\\Dispatch->dispatchCallableMiddleware(Object(Flarum\\Api\\Middleware\\HandleErrors), Object(Zend\\Stratigility\\Next), Object(Zend\\Stratigility\\Http\\Request), Object(Zend\\Stratigility\\Http\\Response), NULL)\n#56 /home/u857997072/public_html/forum/v2/vendor/zendframework/zend-stratigility/src/Next.php(160): Zend\\Stratigility\\Dispatch->__invoke(Object(Zend\\Stratigility\\Route), NULL, Object(Zend\\Stratigility\\Http\\Request), Object(Zend\\Stratigility\\Http\\Response), Object(Zend\\Stratigility\\Next))\n#57 /home/u857997072/public_html/forum/v2/vendor/zendframework/zend-stratigility/src/MiddlewarePipe.php(111): Zend\\Stratigility\\Next->__invoke(Object(Zend\\Stratigility\\Http\\Request), Object(Zend\\Stratigility\\Http\\Response))\n#58 /home/u857997072/public_html/forum/v2/vendor/flarum/core/src/Http/AbstractServer.php(55): Zend\\Stratigility\\MiddlewarePipe->__invoke(Object(Zend\\Stratigility\\Http\\Request), Object(Zend\\Stratigility\\Http\\Response), Object(Zend\\Stratigility\\NoopFinalHandler))\n#59 /home/u857997072/public_html/forum/v2/vendor/zendframework/zend-diactoros/src/Server.php(157): Flarum\\Http\\AbstractServer->__invoke(Object(Zend\\Diactoros\\ServerRequest), Object(Zend\\Diactoros\\Response), Object(Zend\\Stratigility\\NoopFinalHandler))\n#60 /home/u857997072/public_html/forum/v2/vendor/flarum/core/src/Http/AbstractServer.php(36): Zend\\Diactoros\\Server->listen(Object(Zend\\Stratigility\\NoopFinalHandler))\n#61 /home/u857997072/public_html/forum/v2/api.php(16): Flarum\\Http\\AbstractServer->listen()\n#62 {main}"
    }
  ]
}

```
its happen when going to the bazaar tab and get processing

Token : 
```

eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImp0aSI6IjIwODE0OTQ5OGVlMWE3Yzk5NzgxYjk2NWI0ZjJmZDc5ZjMxODA3NGI1NTZhNDRjMjAxNDRlNDQxMGY4MjAwMmFmNGZhZDA0NmEyNzMwYjgwIn0.eyJhdWQiOiIxIiwianRpIjoiMjA4MTQ5NDk4ZWUxYTdjOTk3ODFiOTY1YjRmMmZkNzlmMzE4MDc0YjU1NmE0NGMyMDE0NGU0NDEwZjgyMDAyYWY0ZmFkMDQ2YTI3MzBiODAiLCJpYXQiOjE1MjUzMDczNzgsIm5iZiI6MTUyNTMwNzM3OCwiZXhwIjoxNTU2ODQzMzc4LCJzdWIiOiIiLCJzY29wZXMiOlsicHVibGljOnBhY2thZ2VzX3JlYWQiXX0.Hbs-my-GxZFeiPpu55P0IrjdCMH9EfXciJ5lEDR3xvyKnKv_u3vLmlytGr1s5QTCLrgmcE-vzmv2OIv0H9PTybkP6XxGw31K7uVmSQH9reEcEvK9agJf0pj_ty0xI1F_c3ynuPK0FxRB2l6ULXlT5MwxfNvgcUEQWmSwex5_aj85iZBRv4i-ZkbjkHOmD_6pOgaPORShaOrN1pWvCHy9nMLqYB4VLkaHU4-3sVv_d3smi6O8x4ugCtHEYnsfH7QS4gsW7nYqVteCH_kSzlwEQtptj3jqMQTGOL__fh8b95CeSpTTivoMj1VBOGPM8dlXFfAG2sOLiKfcMq5kAP0OA1FToYLIEIK0qrb_sIK2wgQAE2w-3PQ5aXMHjMhIipeAlS-29vUUSrLiF5Nkc_0XeXylTXmxBe6ZB_areeLz6KJr6j1XWofL_nSB5NMKa_N951tQ1cTzVRUynhs_nGuVeSU--Mwz1n2UTQX-_BBmUUGpGuYbgG52DyRMSqEwNQMqwbs2ZSfglHP1noyWJln_eKpqdU8tmLRFvOZt-E1UKMwR1jRtmhJOqMxKtERZPVHSc5GZ7hQ5E3c9a7Gl54EBLxEKuOH1feFxLYDLX6S0pzyY6Nw0HD4uHh221AjhnPaAppT3kBUyFIFbc9Sn3tJfUEMmLodjZgddWDZoo03ZHuI

```
</details>

**Comment by clarkwinkelmann** [comment]
Bazaar processing takes a fair amount of time and it looks like your database got disconnected in the meantime. Flarum has no means of reconnecting to a database it if lost connection so you get that error.

Did you try multiple times ? It might be a temporary issue.

If it still happens try increasing your database timeout value (there must be a setting in MySQL configuration) or switch the connection mode (try 127.0.0.1 instead of localhost for example).

This doesn't look like an issue with Bazaar itself.

Let us know if you still experience it.

**Comment by clarkwinkelmann** [comment]
Sounds like the same as #52 by the way

**Comment by clarkwinkelmann** [comment]
@KazeroG this sounds like a setting for the max number of clients. There must be something for the max duration of a connection. Maybe you can't change it if it's a managed hosting :grimacing: 

Maybe the issue can be blamed on Flarum after all, seeing the previous report we had in #52

**Comment by KazeroG** [comment]
i reopen this issue because my hoster made a update ! with this update it does give us the possibilities to change some setting maybe related to this issue !
# this is my setting of the moment ! ### what is the best settings ?
![img](https://imgur.com/hbJbZj5)

**Comment by clarkwinkelmann** [comment]
I believe these are all PHP settings. The issue seemed to be with MySQL.

I'm really not sure what's going on with those database issues...

As said in my previous message it might be Flarum doing strange things after all. I think we need to wait for beta8 and see if this continues. Debugging this is requiring too much effort.

Sorry that we can't help more. At this point I would suggest changing hosting if this doesn't work...
